baseurl: "http://www.dyliew.com/blog"
languageCode: "en-us"
title: "DYLiew's Blog"
theme: "hyde"
permalinks:
  post: /:year/:month/:title/
params:
  layoutReverse: false
  themeColor: "theme-base-0c"
  disqusShortname: "dyliew"
  description: "Blog site of DY Liew"
menu:
  main:
      - Name: "Home"
        Pre: "<i class='fa fa-home'></i>"
        Weight: -200
        Identifier: "home"
        URL: "/"
      - Name: "Development"
        Pre: "<i class='fa fa-wrench'></i>"
        Weight: -190
        Identifier: "developmnet"
        URL: "/development/"
      - Name: "Random"
        Pre: "<i class='fa fa-random'></i>"
        Weight: -110
        Identifier: "random"
        URL: "/random/"
