name: Continuos Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint_build:
    name: Lint & Build
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v2
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN_BLOG }}
